language: ruby
rvm:
  - 2.3.3
before_install:
  - sudo apt-get install libopencv-dev imagemagick cmake build-essential libjpeg-dev
  - wget http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.9/opencv-2.4.9.zip
  - unzip opencv-2.4.9.zip
  - cd opencv-2.4.9
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - sudo ldconfig
  - gem update bundler
before_script:
  - bundle install --path=.bundle
script:
  - bundle exec rspec spec/

notifications:
  emails:
    - zuqqhi2@gmail.com
  on_success: always
  on_failure: always
